services:
  db:
    image: postgres:17
    container_name: pinkypie_db
    restart: always
    environment:
      POSTGRES_DB: PINKYPIE
      POSTGRES_USER: proy2
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U proy2 -d PINKYPIE"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: pinkypie_backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: pinkypie_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

volumes:
  postgres_data: